Perform\MediaBundle\Entity\File:
    type: entity
    table: perform_media_file
    repositoryClass: Perform\MediaBundle\Repository\FileRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        bucketName:
            type: string
        type:
            type: string
        status:
            type: smallint
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        locations:
            targetEntity: Perform\MediaBundle\Entity\Location
            mappedBy: file
            cascade:
                - persist
                - remove
    manyToOne:
        owner:
            targetEntity: Perform\UserBundle\Entity\User
            joinColumn:
                nullable: true
