Perform\MediaBundle\Entity\File:
    type: entity
    table: perform_media_file
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
        filename:
            type: string
        type:
            type: string
        typeOptions:
            type: json_array
        mimeType:
            type: string
        charset:
            type: string
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        owner:
            targetEntity: Perform\UserBundle\Entity\User
            joinColumn:
                nullable: true
