Perform\MediaBundle\Entity\Location:
    type: entity
    table: perform_media_extra_location
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        path:
            type: string
        type:
            type: smallint
        attributes:
            type: json_array
    manyToOne:
        file:
            targetEntity: Perform\MediaBundle\Entity\File
            inversedBy: extraLocations
            joinColumn:
                nullable: false
