services:
    admin_media.importer.file:
        class: Admin\MediaBundle\Importer\FileImporter
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    admin_media.plugin.registry:
        class: Admin\MediaBundle\Plugin\PluginRegistry

    admin_media.listener.file_plugin:
        class: Admin\MediaBundle\EventListener\FilePluginListener
        arguments: ["@admin_media.plugin.registry"]
        tags:
            - {name: kernel.event_subscriber}

    admin_media.twig.file:
        class: Admin\MediaBundle\Twig\Extension\FileExtension
        arguments: ["@admin_media.plugin.registry"]
        tags:
            - {name: twig.extension}

    admin_media.url.simple:
        class: Admin\MediaBundle\Url\SimpleFileUrlGenerator
        arguments: [""]

    admin_media.plugin.other:
        class: Admin\MediaBundle\Plugin\OtherPlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@admin_media.url.simple"
        tags:
            - {name: admin_media.file_plugin, pluginName: other}

    admin_media.plugin.pdf:
        class: Admin\MediaBundle\Plugin\PdfPlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@admin_media.url.simple"
        tags:
            - {name: admin_media.file_plugin, pluginName: pdf}

    admin_media.plugin.image:
        class: Admin\MediaBundle\Plugin\ImagePlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@admin_media.url.simple"
        tags:
            - {name: admin_media.file_plugin, pluginName: image}

    admin_media.menu_link.media:
        class: Admin\MediaBundle\Menu\MediaLinkProvider
        tags:
            - { name: admin_base.link_provider, alias: media }
