services:
    perform_media.importer.file:
        class: Perform\MediaBundle\Importer\FileImporter
        arguments:
            - "@perform_media.bucket_registry"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    perform_media.bucket_registry:
        class: Perform\MediaBundle\Bucket\BucketRegistry

    perform_media.twig.file:
        class: Perform\MediaBundle\Twig\Extension\FileExtension
        arguments:
            - "@perform_media.importer.file"
        tags:
            - {name: twig.extension}

    perform_media.url.simple:
        class: Perform\MediaBundle\Url\SimpleUrlGenerator
        arguments: ["/uploads"]

    perform_media.menu_link.media:
        class: Perform\MediaBundle\Menu\MediaLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: media }

    perform_media.listener.download_url:
        class: Perform\MediaBundle\EventListener\DownloadUrlListener
        public: false
        tags:
            - { name: kernel.event_listener, event: perform_media.import_url, method: onImport, priority: -100 }

    perform_media.type.media:
        class: Perform\MediaBundle\Type\MediaType
        arguments:
            - '@perform_media.bucket_registry'
            - '@perform_base.asset_container'
        tags:
            - { name: perform_base.type, alias: media }

    perform_media.repo.file:
        class: Perform\MediaBundle\Repository\FileRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - "PerformMediaBundle:File"

    Perform\MediaBundle\Command\:
        resource: '../../Command'
        public: false
        autowire: true
        autoconfigure: true
