services:
    perform_media.importer.file:
        class: Perform\MediaBundle\Importer\FileImporter
        arguments:
            - "@perform_media.bucket_registry"
            - "@doctrine.orm.entity_manager"
            - "@perform_media.media_type_registry"
            - "@event_dispatcher"

    perform_media.bucket_registry:
        class: Perform\MediaBundle\Bucket\BucketRegistry

    perform_media.media_type_registry:
        class: Perform\MediaBundle\MediaType\MediaTypeRegistry

    perform_media.twig.file:
        class: Perform\MediaBundle\Twig\Extension\FileExtension
        arguments:
            - "@perform_media.importer.file"
        tags:
            - {name: twig.extension}

    perform_media.url.simple:
        class: Perform\MediaBundle\Url\SimpleUrlGenerator
        arguments: ["/uploads"]

    perform_media.media_type.other:
        class: Perform\MediaBundle\MediaType\OtherType
        arguments:
            - "@oneup_flysystem.main_filesystem"
        tags:
            - {name: perform_media.file_plugin, pluginName: other}

    perform_media.media_type.pdf:
        class: Perform\MediaBundle\MediaType\PdfType
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@perform_media.url.simple"
        tags:
            - {name: perform_media.file_plugin, pluginName: pdf}

    perform_media.imagine:
        class: Imagine\Gd\Imagine

    perform_media.media_type.image:
        class: Perform\MediaBundle\MediaType\ImageType
        arguments:
            - "@perform_media.imagine"
            - [100, 400, 1024]
        tags:
            - {name: perform_media.file_plugin, pluginName: image}

    perform_media.media_type.audio:
        class: Perform\MediaBundle\MediaType\AudioType
        arguments:
            - "@oneup_flysystem.main_filesystem"
        tags:
            - {name: perform_media.file_plugin, pluginName: audio}

    perform_media.menu_link.media:
        class: Perform\MediaBundle\Menu\MediaLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: media }

    perform_media.type.media:
        class: Perform\MediaBundle\Type\MediaType
        arguments:
            - "@perform_media.media_type_registry"
            - "@perform_base.asset_container"
        tags:
            - { name: perform_base.type, alias: media }

    Perform\MediaBundle\Command\:
        resource: '../../Command'
        public: false
        autowire: true
        autoconfigure: true
