services:
    perform_media.importer.file:
        class: Perform\MediaBundle\Importer\FileImporter
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    perform_media.plugin.registry:
        class: Perform\MediaBundle\Plugin\PluginRegistry
        arguments:
            - "@perform_media.url.simple"

    perform_media.listener.file_plugin:
        class: Perform\MediaBundle\EventListener\FilePluginListener
        arguments: ["@perform_media.plugin.registry"]
        tags:
            - {name: kernel.event_subscriber}

    perform_media.twig.file:
        class: Perform\MediaBundle\Twig\Extension\FileExtension
        arguments: ["@perform_media.plugin.registry"]
        tags:
            - {name: twig.extension}

    perform_media.url.simple:
        class: Perform\MediaBundle\Url\SimpleFileUrlGenerator
        arguments: ["/uploads"]

    perform_media.plugin.other:
        class: Perform\MediaBundle\Plugin\OtherPlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
        tags:
            - {name: perform_media.file_plugin, pluginName: other}

    perform_media.plugin.pdf:
        class: Perform\MediaBundle\Plugin\PdfPlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@perform_media.url.simple"
        tags:
            - {name: perform_media.file_plugin, pluginName: pdf}

    perform_media.imagine:
        class: Imagine\Gd\Imagine

    perform_media.plugin.image:
        class: Perform\MediaBundle\Plugin\ImagePlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
            - "@perform_media.url.simple"
            - "@perform_media.imagine"
        tags:
            - {name: perform_media.file_plugin, pluginName: image}

    perform_media.plugin.audio:
        class: Perform\MediaBundle\Plugin\AudioPlugin
        arguments:
            - "@oneup_flysystem.main_filesystem"
        tags:
            - {name: perform_media.file_plugin, pluginName: audio}

    perform_media.menu_link.media:
        class: Perform\MediaBundle\Menu\MediaLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: media }

    perform_media.type.media:
        class: Perform\MediaBundle\Type\MediaType
        arguments:
            - "@perform_media.plugin.registry"
            - "@perform_base.asset_container"
        tags:
            - { name: perform_base.type, alias: media }
