services:
    _defaults:
        public: false

    perform_media.importer.file:
        class: Perform\MediaBundle\Importer\FileImporter
        arguments:
            - "@perform_media.bucket_registry"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
    Perform\MediaBundle\Importer\FileImporter: '@perform_media.importer.file'

    perform_media.bucket_registry:
        class: Perform\MediaBundle\Bucket\BucketRegistry

    perform_media.twig.file:
        class: Perform\MediaBundle\Twig\Extension\FileExtension
        arguments:
            - "@perform_media.importer.file"
            - "@perform_media.normalizer.file"
            - "@perform_base.asset_container"
        tags:
            - {name: twig.extension}

    perform_media.url.simple:
        class: Perform\MediaBundle\Url\SimpleUrlGenerator
        arguments: ["/uploads"]

    perform_media.menu_link.media:
        class: Perform\MediaBundle\Menu\MediaLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: media }

    perform_media.listener.download_url:
        class: Perform\MediaBundle\EventListener\DownloadUrlListener
        tags:
            - { name: kernel.event_listener, event: perform_media.import_url, method: onImport, priority: -100 }

    perform_media.type.media:
        class: Perform\MediaBundle\Type\MediaType
        arguments:
            - '@perform_media.bucket_registry'
        tags:
            - { name: perform_base.type, alias: media }

    perform_media.repo.file:
        class: Perform\MediaBundle\Repository\FileRepository
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments:
            - "PerformMediaBundle:File"
    Perform\MediaBundle\Repository\FileRepository: '@perform_media.repo.file'

    perform_media.normalizer.file:
        class: Perform\MediaBundle\Serializer\FileNormalizer
        arguments:
            - "@perform_media.importer.file"
        tags:
            - serializer.normalizer

    Perform\MediaBundle\Controller\:
        resource: '../../Controller'
        autoconfigure: true

    Perform\MediaBundle\Command\:
        resource: '../../Command'
        autowire: true
        autoconfigure: true

    perform_media.form.type.media:
        class: Perform\MediaBundle\Form\Type\MediaType
        arguments:
            - "@perform_base.asset_container"
            - "@perform_media.normalizer.file"
        tags:
            - {name: form.type}
